// Generated by gencpp from file testmsg/Testmag.msg
// DO NOT EDIT!


#ifndef TESTMSG_MESSAGE_TESTMAG_H
#define TESTMSG_MESSAGE_TESTMAG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace testmsg
{
template <class ContainerAllocator>
struct Testmag_
{
  typedef Testmag_<ContainerAllocator> Type;

  Testmag_()
    : left(0.0)
    , right(0.0)  {
    }
  Testmag_(const ContainerAllocator& _alloc)
    : left(0.0)
    , right(0.0)  {
  (void)_alloc;
    }



   typedef float _left_type;
  _left_type left;

   typedef float _right_type;
  _right_type right;





  typedef boost::shared_ptr< ::testmsg::Testmag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::testmsg::Testmag_<ContainerAllocator> const> ConstPtr;

}; // struct Testmag_

typedef ::testmsg::Testmag_<std::allocator<void> > Testmag;

typedef boost::shared_ptr< ::testmsg::Testmag > TestmagPtr;
typedef boost::shared_ptr< ::testmsg::Testmag const> TestmagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::testmsg::Testmag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::testmsg::Testmag_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace testmsg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'testmsg': ['/home/rain/ydlidar_ws/src/testmsg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::testmsg::Testmag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::testmsg::Testmag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testmsg::Testmag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::testmsg::Testmag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testmsg::Testmag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::testmsg::Testmag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::testmsg::Testmag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3a927990ab5d5c3d628e2d52b8533e52";
  }

  static const char* value(const ::testmsg::Testmag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3a927990ab5d5c3dULL;
  static const uint64_t static_value2 = 0x628e2d52b8533e52ULL;
};

template<class ContainerAllocator>
struct DataType< ::testmsg::Testmag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "testmsg/Testmag";
  }

  static const char* value(const ::testmsg::Testmag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::testmsg::Testmag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left\n\
float32 right\n\
";
  }

  static const char* value(const ::testmsg::Testmag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::testmsg::Testmag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left);
      stream.next(m.right);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Testmag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::testmsg::Testmag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::testmsg::Testmag_<ContainerAllocator>& v)
  {
    s << indent << "left: ";
    Printer<float>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<float>::stream(s, indent + "  ", v.right);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TESTMSG_MESSAGE_TESTMAG_H
